# Git
alias gitadd='git add'
alias gitbranch='git branch'
alias gitcheckout='git checkout'
alias gitcommit='git commit -m'
alias gitdiff='git diff'
alias gitfetch='git fetch'
alias gitfetchoriginprune='git fetch origin -p'
alias gitlog='git log'
alias gitpull='git pull'
alias gitpush='git push'
alias gitstatus='git status'
